config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      render :index
    else
      render :new
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_flat
    @flat = Flat.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def flat_params
    params.require(:flat).permit(:name, :address, :phone_number, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<!-- app/views/layouts/application.html.erb -->
<head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
</head>


<body>
  <h1 class="allflats">All our flats (<%= @flats.count %>)</h1>
  <div class="row">
    <div class="col 12 card-container">
      <% @flats.each do |flat| %>
        <div class="card-apt-info">
          <div class="card-apt">
            <h3><%= flat.name  %></h3>
            <p><%= flat.address %></p>
            <div class="card-numeric-info">
              <i class="fas fa-user-friends"></i>
              <p> <%= flat.number_of_guests %></p>
              <i class="fas fa-euro-sign"></i>
              <p><%= flat.price_per_night %></p>
            </div>
          </div>
          <div class="card-more-info">
            <p>More info</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/flats/new.html.erb
        <h1 class="addflat">Add a new flat</h1>

<div class="container">
  <div class="row">
    <div class="col">
      <%= simple_form_for @flat do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description%>
        <%= f.input :price_per_night %>
        <%= f.input :number_of_guests %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar-lewagon">
      <p>Simple Airbnb</p>
      <div class="btn btn-primary">
        <%= link_to "Add flat", new_flat_path %>
       </div>
    </div>

    <%= yield %>
  </body>
</html>